export const THEME = {
   COLORS: {
      primaryLightBackground: "#F7F7F7",
      secondaryDarkBackground: "#2F3B52",
      secondaryLightBackground: "#ffffff",
      primaryBgColor: ["#033968", "#154D79", "#033968", "#01182A"],
      textColor: "#FFFFFF",
      placeHolderColor: "#BBBCBD",
      authtextColor: "#B4B5BA",
      textInputBgColor: "#1A2434",
      primaryColor: "#01182A",
      chosePhotoColor: "#01182A",
      selectCircle: "#D1D1D1",
      otpCirlce: "#05213B",
      newChatbg: "#01182AE5",
      searchinputClr: "#1A2434",
   },
   LightTHEME: {
      primaryLightBackground: "#F5F5F5",
      secondaryDarkBackground: "#2F3B52",
      secondaryLightBackground: "#ffffff",
      primaryBgColor: ["#033968", "#154D79", "#033968", "#01182A"],
      textColor: "#01182A",
      placeHolderColor: "#BBBCBD",
      authtextColor: "#646464",
      textInputBgColor: "#F2F2F2",
      primaryColor: "#01182A",
      chosePhotoColor: "#01182A",
      selectCircle: "#D1D1D1",
      otpCirlce: "#F2F2F2",
      newChatbg: "#01182AE5",
      searchinputClr: "#1A2434",
   },
   //    FONTS: {
   //       SIZE: {
   //          XXLARGE: 32,
   //          XLARGE: 24,
   //          LARGE: 20,
   //          MEDIUM: 18,
   //          SMALL: 16,
   //          XSMALL: 14,
   //          XXSMALL: 12,
   //          XXXSMALL: 10,
   //          XXXXSMALL: 8,
   //       },
   //       TYPE: {
   //          LIGHT: "Lato-Light",
   //          REGULAR: "Lato-Regular",
   //          MEDIUM: "Lato-Bold",
   //          SEMIBOLD: "Lato-Bold",
   //          BOLD: "Lato-Black",
   //       },
   //    },
   //    MARGIN: {
   //       SUPERLOW: 2,
   //       VERYLOW: 4,
   //       LOW: 8,
   //       MID_LOW: 12,
   //       NORMAL: 16,
   //       HIGH: 24,
   //       VERYHIGH: 32,
   //       SUPERHIGH: 48,
   //       NOVAHIGH: 60,
   //    },
   PADDING: {
      SUPERLOW: 2,
      VERYLOW: 4,
      LOW: 8,
      NORMAL: 16,
      HIGH: 24,
      VERYHIGH: 32,
      SUPERHIGH: 48,
   },
};
